config/routes.rb
Rails.application.routes.draw do
  resources :gists
  resource :session, only: [:new, :create, :destroy]
  root to: 'welcome#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  validates :title, :body, presence: true

  scope :published, -> {where(secret: false)}
  
  def body_html(lang = :ruby)
    html = CodeRay.scan(body, lang)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :gists

  def title
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def signed_in?
    current_user
  end
  helper_method :signed_in?
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]

  # GET /gists
  # GET /gists.json
  def index
    @gists = Gist.all
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = current_user.gists.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render :show, status: :created, location: @gist }
      else
        format.html { render :new }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { render :show, status: :ok, location: @gist }
      else
        format.html { render :edit }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url, notice: 'Gist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:title, :body, :secret, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @hello = 'Hello World'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gists/_form.html.slim
h1 Гист
br
= simple_form_for(@gist) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :body
    = f.input :secret
    / = f.association :user

  .form-actions
    = f.button :submit, 'Сохранить', class: 'btn btn-primary'

app/views/gists/edit.html.slim
== render 'form'

app/views/gists/index.html.slim
h1
  'Все гисты
  - if signed_in?
    = link_to 'New Gist', new_gist_path, class: 'btn btn-primary'

br

table.table
  thead
    tr
      th Gist
      th Secret
      th User
      th
      th
      th

  tbody
    - @gists.each do |gist|
      tr
        td 
          
          .card
            .card-header
              = gist.title
              '
              = link_to 'Edit', edit_gist_path(gist), class: 'btn btn-sm btn-secondary'
            .card-block
              = gist.body_html.div.html_safe
              hr
              .btn-group.btn-group-sm
                = link_to 'Show', gist, class: 'btn btn-secondary'
                = link_to 'Destroy', gist, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'
              
        td = gist.user.email
          
        td = link_to 'Show', gist
        td = link_to 'Edit', edit_gist_path(gist)
        td = link_to 'Destroy', gist, data: { confirm: 'Are you sure?' }, method: :delete

br

app/views/gists/new.html.slim
== render 'form'

app/views/gists/show.html.slim
p#notice = notice

p
  strong Title:
  = @gist.title
p
  strong Body:
.card.card-block
  = @gist.body_html.div.html_safe
p
  strong Secret:
  = @gist.secret
p
  strong User:
  = @gist.user.email

= link_to 'Edit', edit_gist_path(@gist)
'  |
= link_to 'Back', gists_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title GistAppDemo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
  body 
    .container
      nav.nav
        = link_to 'Главная', root_path, class: 'nav-link'
        - if signed_in?
          = link_to 'Гисты', gists_path, class: 'nav-link'
          = link_to current_user.email, '#', class: 'nav-link'
          = link_to 'Выход', session_path, method: :delete, class: 'nav-link'
        - else
          = link_to 'Вход', new_session_path, class: 'nav-link'
        
      hr
      
      = yield

app/views/welcome/home.html.slim
center
  h1 Привет!

hr  
p
  = @hello


table.table
  - Gist.published.each do |gist|
    tr
      td = link_to gist.title, gist